name: PulseMC Pipeline
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ver/1.21.4  # явно указываем ветку
