name: Build Pulse

on:
  workflow_dispatch:  # запуск вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Apply patches
        run: ./gradlew applyAllPatches

      - name: Build JAR
        run: ./gradlew createReobfPaperclipJar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pulse-Leaf-1.21.4
          path: build/libs/*.jar
